In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

print("✅ Libraries imported successfully")

✅ Libraries imported successfully

In [10]:
weather = pd.read_csv("lga_weather_2022.csv")
weather.head()

         date  AWND  PRCP  TMAX  TMIN
0  2022-01-01   2.8  19.3  13.9  10.0
1  2022-01-02   4.3   1.0  15.6   3.9
2  2022-01-03   6.4   0.0   3.9  -4.3
3  2022-01-04   3.9   0.0   2.2  -6.0
4  2022-01-05   3.4   6.1   8.9   0.0

In [11]:
bike = pd.read_csv("citibike_2022_merged_weather.csv")
bike.head()

/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_1687/2965528967.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.read_csv("citibike_2022_merged_weather.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,AWND,PRCP,TMAX,TMIN
0,3A2034DA67C8874B,electric_bike,2022-09-14 20:37:39.155,2022-09-14 21:05:39.760,N 12 St & Bedford Ave,5450.04,Albany St & Greenwich St,5145.02,40.720796,-73.954882,40.709267,-74.013247,casual,2022-09-14,5.2,0.0,26.7,18.3
1,F1C63DACDCC1C33D,electric_bike,2022-09-17 19:21:39.407,2022-09-17 20:08:32.670,Union Ave & Jackson St,5300.06,Metropolitan Ave & Meeker Ave,5300.05,40.716075,-73.952029,40.714133,-73.952344,casual,2022-09-17,4.2,0.0,23.3,18.3
2,94372C52777F4AC1,electric_bike,2022-09-17 16:49:21.830,2022-09-17 17:01:51.537,S 4 St & Wythe Ave,5204.05,St Marks Pl & 1 Ave,5626.13,40.712874,-73.965935,40.727791,-73.985649,casual,2022-09-17,4.2,0.0,23.3,18.3
3,44818FEC94B62B66,electric_bike,2022-09-08 12:27:40.019,2022-09-08 12:47:15.649,Amsterdam Ave & W 73 St,7260.09,Washington St & Gansevoort St,6039.06,40.779668,-73.980930,40.739323,-74.008119,casual,2022-09-08,3.5,0.0,25.6,18.3
4,F8A63709F214EBAA,classic_bike,2022-09-16 19:00:19.266,2022-09-16 19:07:28.905,University Pl & E 14 St,5905.14,Washington St & Gansevoort St,6039.06,40.734814,-73.992085,40.739323,-74.008119,member,2022-09-16,2.6,0.0,25.0,15.0

In [12]:
# Convert date columns

weather["date"] = pd.to_datetime(weather["date"])

bike["started_at"] = pd.to_datetime(bike["started_at"])
bike["ended_at"] = pd.to_datetime(bike["ended_at"])

print("✅ Date columns converted")

✅ Date columns converted

In [13]:
bike["value"] = 1
bike[["value"]].head()

   value
0      1
1      1
2      1
3      1
4      1

In [14]:
trips_agg = (
    bike.groupby(["start_station_name", "end_station_name"])["value"]
        .count()
        .reset_index(name="trips")
)

trips_agg.head()

  start_station_name   end_station_name  trips
0   1 Ave & E 110 St   1 Ave & E 110 St     96
1   1 Ave & E 110 St    1 Ave & E 30 St      1
2   1 Ave & E 110 St    1 Ave & E 94 St     13
3   1 Ave & E 110 St  10 Ave & W 215 St      1
4   1 Ave & E 110 St   2 Ave & E 104 St      2

In [15]:
print("Total trips in original bike data:", bike.shape[0])
print("Sum of trips in aggregated data:", trips_agg["trips"].sum())

Total trips in original bike data: 1163216
Sum of trips in aggregated data: 1155488

In [16]:
bike = bike.dropna(subset=["start_station_name", "end_station_name"])
print("Trips after removing missing stations:", bike.shape[0])

Trips after removing missing stations: 1155488

In [17]:
bike["value"] = 1

trips_agg = (
    bike.groupby(["start_station_name", "end_station_name"])["value"]
        .count()
        .reset_index(name="trips")
)

print("Sum of trips in aggregated data:", trips_agg["trips"].sum())

Sum of trips in aggregated data: 1155488

In [18]:
import sys
!{sys.executable} -m pip install keplergl

Requirement already satisfied: keplergl in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (0.3.7)
Requirement already satisfied: ipywidgets>=8.1.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (8.1.8)
Requirement already satisfied: traittypes>=0.2.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.2.3)
Requirement already satisfied: traitlets>=4.3.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (5.14.3)
Requirement already satisfied: geopandas>=0.14.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (1.1.2)
Requirement already satisfied: Shapely>=1.6.4.post2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (2.1.2)
Requirement already satisfied: jupyter_packaging>=0.12.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.12.3)
Requirement already satisfied: jupyter>=1.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (1.1.1)
Requirement already satisfied: jupyterlab>=4.1.6 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (4.5.3)
Requirement already satisfied: notebook>=6.0.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (7.5.3)
Requirement already satisfied: pyarrow>=16.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (23.0.0)
Requirement already satisfied: geoarrow-pyarrow>=0.1.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.2.0)
Requirement already satisfied: geoarrow-pandas>=0.1.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.1.1)
Requirement already satisfied: pandas in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geoarrow-pandas>=0.1.1->keplergl) (2.3.3)
Requirement already satisfied: geoarrow-types>=0.3.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geoarrow-pyarrow>=0.1.2->keplergl) (0.3.0)
Requirement already satisfied: geoarrow-c>=0.3.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geoarrow-pyarrow>=0.1.2->keplergl) (0.3.1)
Requirement already satisfied: numpy>=1.24 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (2.2.6)
Requirement already satisfied: pyogrio>=0.7.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (0.12.1)
Requirement already satisfied: packaging in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (3.7.1)
Requirement already satisfied: comm>=0.1.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (8.38.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (3.0.16)
Requirement already satisfied: decorator in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (5.2.1)
Requirement already satisfied: exceptiongroup in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (2.19.2)
Requirement already satisfied: stack_data in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (4.15.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.5.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.8.5)
Requirement already satisfied: jupyter-console in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter>=1.0.0->keplergl) (6.6.3)
Requirement already satisfied: nbconvert in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter>=1.0.0->keplergl) (7.16.6)
Requirement already satisfied: ipykernel in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter>=1.0.0->keplergl) (7.1.0)
Requirement already satisfied: deprecation in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (2.1.0)
Requirement already satisfied: setuptools>=60.2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (78.1.1)
Requirement already satisfied: tomlkit in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (0.14.0)
Requirement already satisfied: wheel in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (0.45.1)
Requirement already satisfied: async-lru>=1.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.1.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (3.1.6)
Requirement already satisfied: jupyter-core in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (0.2.4)
Requirement already satisfied: tomli>=1.2.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.4.0)
Requirement already satisfied: tornado>=6.2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (6.5.4)
Requirement already satisfied: anyio in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (4.12.1)
Requirement already satisfied: certifi in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (25.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (8.8.0)
Requirement already satisfied: jupyter-events>=0.11.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.24.1)
Requirement already satisfied: pyzmq>=24 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.9.0)
Requirement already satisfied: babel>=2.10 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (0.13.0)
Requirement already satisfied: jsonschema>=4.18.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (4.26.0)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2.32.5)
Requirement already satisfied: argon2-cffi-bindings in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (25.1.0)
Requirement already satisfied: appnope>=0.1.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (0.1.4)
Requirement already satisfied: debugpy>=1.6.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (1.8.19)
Requirement already satisfied: nest-asyncio>=1.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (1.6.0)
Requirement already satisfied: psutil>=5.7 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (7.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jinja2>=3.0.3->jupyterlab>=4.1.6->keplergl) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (0.30.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-core->jupyterlab>=4.1.6->keplergl) (4.5.1)
Requirement already satisfied: python-json-logger>=2.0.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (6.0.3)
Requirement already satisfied: rfc3339-validator in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.1.1)
Requirement already satisfied: fqdn in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.5.1)
Requirement already satisfied: isoduration in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.1.0)
Requirement already satisfied: uri-template in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (25.10.0)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->keplergl) (6.3.0)
Requirement already satisfied: defusedxml in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (1.5.1)
Requirement already satisfied: webencodings in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->keplergl) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->keplergl) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (2.21.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from pandas->geoarrow-pandas>=0.1.1->keplergl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from pandas->geoarrow-pandas>=0.1.1->keplergl) (2025.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.7.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2.6.3)
Requirement already satisfied: lark>=1.2.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.3.1)

In [19]:
from keplergl import KeplerGl

In [20]:
m = KeplerGl(height=600, data={"Trips": trips_agg})
m

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(data={'Trips':            start_station_name          end_station_name  trips
0            1 Ave & E …

In [21]:
import sys
!{sys.executable} -m pip install -U ipywidgets jupyterlab_widgets widgetsnbextension

Requirement already satisfied: ipywidgets in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (8.1.8)
Requirement already satisfied: jupyterlab_widgets in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (3.0.16)
Requirement already satisfied: widgetsnbextension in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (4.0.15)
Requirement already satisfied: comm>=0.1.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets) (8.38.0)
Requirement already satisfied: traitlets>=4.3.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: decorator in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: exceptiongroup in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.15.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.5.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)

In [22]:
from keplergl import KeplerGl

m = KeplerGl(height=600, data={"Trips": trips_agg})
m

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(data={'Trips':            start_station_name          end_station_name  trips
0            1 Ave & E …

In [23]:
import sys, ipywidgets
print("Python:", sys.executable)
print("ipywidgets:", ipywidgets.__version__)

Python: /opt/anaconda3/envs/citibike_weather/bin/python
ipywidgets: 8.1.8

In [24]:
import sys
!{sys.executable} -m pip install -U keplergl

Requirement already satisfied: keplergl in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (0.3.7)
Requirement already satisfied: ipywidgets>=8.1.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (8.1.8)
Requirement already satisfied: traittypes>=0.2.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.2.3)
Requirement already satisfied: traitlets>=4.3.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (5.14.3)
Requirement already satisfied: geopandas>=0.14.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (1.1.2)
Requirement already satisfied: Shapely>=1.6.4.post2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (2.1.2)
Requirement already satisfied: jupyter_packaging>=0.12.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.12.3)
Requirement already satisfied: jupyter>=1.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (1.1.1)
Requirement already satisfied: jupyterlab>=4.1.6 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (4.5.3)
Requirement already satisfied: notebook>=6.0.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (7.5.3)
Requirement already satisfied: pyarrow>=16.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (23.0.0)
Requirement already satisfied: geoarrow-pyarrow>=0.1.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.2.0)
Requirement already satisfied: geoarrow-pandas>=0.1.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from keplergl) (0.1.1)
Requirement already satisfied: pandas in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geoarrow-pandas>=0.1.1->keplergl) (2.3.3)
Requirement already satisfied: geoarrow-types>=0.3.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geoarrow-pyarrow>=0.1.2->keplergl) (0.3.0)
Requirement already satisfied: geoarrow-c>=0.3.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geoarrow-pyarrow>=0.1.2->keplergl) (0.3.1)
Requirement already satisfied: numpy>=1.24 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (2.2.6)
Requirement already satisfied: pyogrio>=0.7.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (0.12.1)
Requirement already satisfied: packaging in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (26.0)
Requirement already satisfied: pyproj>=3.5.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from geopandas>=0.14.3->keplergl) (3.7.1)
Requirement already satisfied: comm>=0.1.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (8.38.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipywidgets>=8.1.5->keplergl) (3.0.16)
Requirement already satisfied: decorator in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (5.2.1)
Requirement already satisfied: exceptiongroup in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (2.19.2)
Requirement already satisfied: stack_data in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (4.15.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.5.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.8.5)
Requirement already satisfied: jupyter-console in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter>=1.0.0->keplergl) (6.6.3)
Requirement already satisfied: nbconvert in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter>=1.0.0->keplergl) (7.16.6)
Requirement already satisfied: ipykernel in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter>=1.0.0->keplergl) (7.1.0)
Requirement already satisfied: deprecation in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (2.1.0)
Requirement already satisfied: setuptools>=60.2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (78.1.1)
Requirement already satisfied: tomlkit in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (0.14.0)
Requirement already satisfied: wheel in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter_packaging>=0.12.3->keplergl) (0.45.1)
Requirement already satisfied: async-lru>=1.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.1.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (3.1.6)
Requirement already satisfied: jupyter-core in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (0.2.4)
Requirement already satisfied: tomli>=1.2.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (2.4.0)
Requirement already satisfied: tornado>=6.2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab>=4.1.6->keplergl) (6.5.4)
Requirement already satisfied: anyio in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (4.12.1)
Requirement already satisfied: certifi in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab>=4.1.6->keplergl) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (25.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (8.8.0)
Requirement already satisfied: jupyter-events>=0.11.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.24.1)
Requirement already satisfied: pyzmq>=24 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.9.0)
Requirement already satisfied: babel>=2.10 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (0.13.0)
Requirement already satisfied: jsonschema>=4.18.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (4.26.0)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2.32.5)
Requirement already satisfied: argon2-cffi-bindings in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (25.1.0)
Requirement already satisfied: appnope>=0.1.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (0.1.4)
Requirement already satisfied: debugpy>=1.6.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (1.8.19)
Requirement already satisfied: nest-asyncio>=1.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (1.6.0)
Requirement already satisfied: psutil>=5.7 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from ipykernel->jupyter>=1.0.0->keplergl) (7.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jinja2>=3.0.3->jupyterlab>=4.1.6->keplergl) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (0.30.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-core->jupyterlab>=4.1.6->keplergl) (4.5.1)
Requirement already satisfied: python-json-logger>=2.0.4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (6.0.3)
Requirement already satisfied: rfc3339-validator in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (0.1.1)
Requirement already satisfied: fqdn in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.5.1)
Requirement already satisfied: isoduration in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.1.0)
Requirement already satisfied: uri-template in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (25.10.0)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->keplergl) (6.3.0)
Requirement already satisfied: defusedxml in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbconvert->jupyter>=1.0.0->keplergl) (1.5.1)
Requirement already satisfied: webencodings in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->keplergl) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->keplergl) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (2.21.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from pandas->geoarrow-pandas>=0.1.1->keplergl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from pandas->geoarrow-pandas>=0.1.1->keplergl) (2025.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets>=8.1.5->keplergl) (0.7.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab>=4.1.6->keplergl) (2.6.3)
Requirement already satisfied: lark>=1.2.2 in /opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab>=4.1.6->keplergl) (1.3.1)

In [25]:
from keplergl import KeplerGl

m = KeplerGl(height=600, data={"Trips": trips_agg})
m

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

KeplerGl(data={'Trips':            start_station_name          end_station_name  trips
0            1 Ave & E …

In [26]:
from keplergl import KeplerGl

m = KeplerGl(height=600, data={"Trips": trips_agg})

# Save and open in browser (HTML output)
m.save_to_html(file_name="trips_kepler_map.html", read_only=False)
print("✅ Map saved as trips_kepler_map.html — open it from your project folder.")

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
Map saved to trips_kepler_map.html!
✅ Map saved as trips_kepler_map.html — open it from your project folder.

In [27]:
import os
print(os.getcwd())

/Users/saraseid

In [28]:
from keplergl import KeplerGl

m = KeplerGl(height=600, data={"Trips": bike})
m.save_to_html(file_name="trips_kepler_map.html", read_only=False)

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

/opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages/jupyter_client/session.py:727: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)

Map saved to trips_kepler_map.html!

In [30]:
from keplergl import KeplerGl

m = KeplerGl(height=600, data={"Trips": bike})
m.save_to_html(file_name="trips_kepler_map.html", read_only=False)
print("New map saved with coordinates ✅")

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

/opt/anaconda3/envs/citibike_weather/lib/python3.10/site-packages/jupyter_client/session.py:727: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)

Map saved to trips_kepler_map.html!
New map saved with coordinates ✅

In [31]:
bike_small = bike.sample(20000, random_state=42)  # only 20k rows

from keplergl import KeplerGl
m = KeplerGl(height=600, data={"Trips": bike_small})
m.save_to_html(file_name="trips_kepler_map.html", read_only=False)

print("Smaller map saved ✅")

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
Map saved to trips_kepler_map.html!
Smaller map saved ✅

In [11]:
import pandas as pd
from glob import glob

trip_folder = "/Users/saraseid/Desktop/citibike-weather-project/2022-citibike-tripdata"

csv_files = sorted(glob(trip_folder + "/*.csv"))
len(csv_files), csv_files[:3]

(36,
 ['/Users/saraseid/Desktop/citibike-weather-project/2022-citibike-tripdata/202201-citibike-tripdata_1.csv',
  '/Users/saraseid/Desktop/citibike-weather-project/2022-citibike-tripdata/202201-citibike-tripdata_2.csv',
  '/Users/saraseid/Desktop/citibike-weather-project/2022-citibike-tripdata/202202-citibike-tripdata_1.csv'])

In [12]:
bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
bike.shape

/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)
/var/folders/r7/hpnbv35s3194ffb_bhsw50nc0000gn/T/ipykernel_72881/3054130295.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike = pd.concat((pd.read_csv(f) for f in csv_files), ignore_index=True)

(29838806, 13)

In [17]:
needed = ["start_station_name","end_station_name","start_lat","start_lng","end_lat","end_lng"]
bike = bike[needed].dropna()
bike.head()

,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng
0,West End Ave & W 107 St,Mt Morris Park W & W 120 St,40.802117,-73.968181,40.804038,-73.945925
1,4 Ave & 3 St,Boerum Pl\t& Pacific St,40.673746,-73.985649,40.688489,-73.991160
2,1 Ave & E 62 St,5 Ave & E 29 St,40.761227,-73.960940,40.745168,-73.986831
3,2 Ave & E 96 St,5 Ave & E 29 St,40.783964,-73.947167,40.745168,-73.986831
4,6 Ave & W 34 St,5 Ave & E 29 St,40.749640,-73.988050,40.745168,-73.986831

In [18]:
# Create trip count column
bike["value"] = 1

# Step 1 — Group ONLY by station names
routes = (
    bike.groupby(["start_station_name", "end_station_name"])
        .size()
        .reset_index(name="trips")
)

# Step 2 — Keep ONE coordinate pair per route
coords = (
    bike[["start_station_name","end_station_name","start_lat","start_lng","end_lat","end_lng"]]
        .drop_duplicates(subset=["start_station_name","end_station_name"])
)

# Step 3 — Merge counts with coordinates
routes = routes.merge(coords, on=["start_station_name","end_station_name"], how="left")

# Step 4 — Limit to top 500 busiest routes
routes_top500 = routes.sort_values("trips", ascending=False).head(500).reset_index(drop=True)

routes_top500.head()

,start_station_name,end_station_name,trips,start_lat,start_lng,end_lat,end_lng
0,Central Park S & 6 Ave,Central Park S & 6 Ave,12041,40.765909,-73.976342,40.765909,-73.976342
1,7 Ave & Central Park South,7 Ave & Central Park South,8541,40.766741,-73.979069,40.766741,-73.979069
2,Roosevelt Island Tramway,Roosevelt Island Tramway,8213,40.757284,-73.953600,40.757284,-73.953600
3,Grand Army Plaza & Central Park S,Grand Army Plaza & Central Park S,7287,40.764397,-73.973715,40.764397,-73.973715
4,Soissons Landing,Soissons Landing,7275,40.692317,-74.014866,40.692317,-74.014866

### from keplergl import KeplerGl

m = KeplerGl(height=600, data={"Trips": trips_agg})
m

In [34]:
from keplergl import KeplerGl

m = KeplerGl(height=600, data={"Trips": trips_agg})
m.save_to_html(file_name="trips_kepler_map.html", read_only=False)
print("saved")

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
Map saved to trips_kepler_map.html!
saved

In [35]:
trips_agg.columns

Index(['start_station_name', 'end_station_name', 'start_lat', 'start_lng',
       'end_lat', 'end_lng', 'trips'],
      dtype='object')

In [36]:
trips_agg[["trips"]].head()

   trips
0      1
1      1
2     82
3      1
4      1

In [37]:
from keplergl import KeplerGl

m = KeplerGl(height=650, data={"Trips": trips_agg})
m.save_to_html(file_name="trips_kepler_map.html", read_only=False)
print("✅ Saved new trips_kepler_map.html")

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
Map saved to trips_kepler_map.html!
✅ Saved new trips_kepler_map.html

I created separate point layers for start and end stations to show where trips begin and end. I then added an Arc layer connecting the stations to represent trip flows. I set the arc color based on the trips field so that darker arcs represent routes with higher usage. This makes it easy to visually identify the most frequently traveled routes between bike stations.

After applying a filter for the most frequent trips, the map shows a dense cluster of bike activity in New York City. The busiest routes are concentrated in a small urban area, indicating short trips between nearby stations. This suggests that bike-sharing is mainly used for commuting and quick travel in densely populated, well-connected parts of the city

In [39]:
config = m.config

In [40]:
m.save_to_html(
    file_name='nyc_trips_kepler_map.html',
    read_only=False,
    config=config
)

Map saved to nyc_trips_kepler_map.html!

In [20]:
routes_top500.to_csv("routes_top500.csv", index=False)